### ISSUE TITLE
Error while assigning java script variable to r variable

### ISSUE THREAD

**Issue by bhagatd800** [cscheid/rserve-js#34]
I am confused whether i can assign javascript variable to R variable.

var disease="fever";
client.assign("'x', disease"); or 
client.assign("x", disease);
client.eval("print(x)")
Both doesnot work

this the error i get
Error: ignoring SIGPIPE signal
*** stack smashing detected ***: /usr/local/lib/R/site-library/Rserve/libs//Rserve terminated
Am i doing it wrong or whether this kind of facility is not provided in the Rserve-js

**Comment by s-u** [comment]
The error is secondary - `SIGPIPE` means that you closed the connection - your JS code fails first, because there is no `assign()` - the method is `set()`.
